### ISSUE TITLE
Unable to fit and how to get growth parameters from fitting

### ISSUE THREAD

**Issue by martacn** [briandconnelly/growthcurve#5]
Hi,

I have been testing your package recently and seems more handy that grofit it self. It seems I cannot find out how to get growth parameters such as mu and lambda when fit_growth function is called. Could you explain briefly how to extract growth parameters from fitting?

On the other hand, the data im fitting are OD's determined each 2h. I use corrected OD's where the blank has been subtracted so initial values are close to 0 like (0.001 or 0.01). The fitting fails when the corrected values are used. However, fit success when raw data is used (blank not subtracted) so initial values in first 4-6h are like 0.100.  Same happens in grofit package. Could you explain why this is happening and if there's a way to mitigate this rather than using raw data which would be my last choice.

Thank you :)

**Comment by briandconnelly** [comment]
I'm glad you asked this---I'll definitely have to add info about getting the parameters to the README.

You'll want to save the result of `fit_growth`. For example:

```r
library(growthcurve)
library(dplyr)

pdata1 <- pseudomonas %>%
    filter(Replicate == 1 & Strain == "PAO1")

m1 <- fit_growth(pdata1, Time, CFUmL)
```

The parameters are stored in `m1$parameters` (`m1$parameters$asymptote`, `m1$parameters$max_rate`, and `m1$parameters$augc`)

Does that work for you?

**Comment by martacn** [comment]
Yep, thank you!
